apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sentiment-monitor
  namespace: default
  labels:
    release: prometheus  # Это связывает мониторинг с вашим релизом Helm
spec:
  selector:
    matchLabels:
      app: sentiment     # Должен совпадать с селектором Service
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: web            # <--- Ссылается на имя порта "web" из Service.yaml
      path: /actuator/prometheus
      interval: 15s